### ISSUE TITLE
Unhandled 404 error when try save instance

### ISSUE THREAD

**Issue by DmitriyDmytruk** [NoelDeMartin/soukai-solid#11]
I have the following model.
```
export default class Block extends SolidModel {
    static rdfContexts = {
        'hdf': DICTIONARY
    }

    static rdfsClasses = [
        'hdf:Block'
    ]
}

export default class Transcription extends Block {
    static type: string = 'transcription';

    static rdfsClasses = [
        'Transcription'
    ]
}
```

I receive data by websocket  and store it. But I get an error. Although the data in the pod is saved and the url exists.

Here is a screen of requests. It looks very strange. Why I see did these 2 `get requests`...
And first two get requests leave, and then the patch.

![image](https://user-images.githubusercontent.com/62432498/112005842-cd59c880-8b2b-11eb-9ab9-1871e724ae3c.png)
![image](https://user-images.githubusercontent.com/62432498/112005857-d185e600-8b2b-11eb-9a37-d50ab6dab297.png)
![image](https://user-images.githubusercontent.com/62432498/112005870-d5196d00-8b2b-11eb-83e3-d05c7376d399.png)
![image](https://user-images.githubusercontent.com/62432498/112005886-d9458a80-8b2b-11eb-93f1-ba445d63c2f5.png)

Saving looks like this.
```
const transcription = new Transcription({content: event.data});
transcription.save('https://<my_link>/stories/');
```
I wrapped in tray/catch. Nothing gets into the catch... It feels like there is no mistake at all...

**Comment by NoelDeMartin** [comment]
I'm not sure why you have two GET requests, but one of them is the expected behavior. Maybe it has something to do with your app, because you're getting the two GET requests from different parts of the code (one of them from Fetcher.ts and the other one from service-worker.js).

Now, as to why one GET request is the expected behaviour, that's because before creating a new document I'm checking if it exists or not (to avoid overwriting it): https://github.com/NoelDeMartin/soukai-solid/blob/main/src/engines/SolidEngine.ts#L54 I know it's annoying to see that error in the console, but that's just how browsers work. As far as I know, you can't silence that error after getting a 404 response, even if I am handling the error properly.

Technically, that shouldn't be necessary because I am using the `If-None-Match` header [in the PATCH request](https://github.com/NoelDeMartin/soukai-solid/blob/e4d0e918ba64a2454cfbe1d1ca6ce8ef6287fc4d/src/solid/SolidClient.ts#L226), and that should avoid overwriting documents. But it doesn't seem to be supported in all Solid PODs so I'm leaving it there until I'm sure it works everywhere: https://github.com/solid/node-solid-server/issues/1431

By the way, one comment about your code is that I'm not 100% sure that extending Model classes like that will work (rdfsClasses may get overwritten for example). It should work by design, but I haven't actually done that in my apps so keep it in mind if something isn't working. Feel free to open issues if you find them :).
