### ISSUE TITLE
example works with pod.inrupt.net but not with solid.community

### ISSUE THREAD

**Issue by scenaristeur** [NoelDeMartin/soukai-solid#14]
Hello @NoelDeMartin 

this example on pod.inrupt.net https://codesandbox.io/s/u4zh2?file=/src/index.ts
does not seem to work with a webId on solidcommunity : https://spoggy-test2.solidcommunity.net/profile/card#me
does not work https://codesandbox.io/s/soukai-solid-testing-forked-hdujl2?file=/src/index.ts

and this one does not seem to work too https://codesandbox.io/s/3btgd
nor this one https://codesandbox.io/s/km6wl

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening an issue!

I've looked into it, and it seems like you've run into an actual bug. Thanks for reporting it :).

I noticed that the following turtle syntax was not being parsed properly, and that's why it fails in solidcommunity but works on inrupt:

```turtle
acl:trustedApp
    [
        acl:mode acl:Append, acl:Read, acl:Write;
        acl:origin <https://one.example.app>
    ],
    [
        acl:mode acl:Append, acl:Read, acl:Write;
        acl:origin <https://two.example.app>
    ];
```

I've fixed it in the [next](https://github.com/NoelDeMartin/soukai-solid/tree/next) branch, but I don't think I'll do a release for a while because I've been working on the next major version for some time and it has some rough edges (among other things, I have to document the breaking changes and all that). So I'm afraid you'll have to wait to use this fix. It'll probably take some months, but hopefully it should happen before 2023. 

Now, if you're feeling adventurous you can install the `next` version which already includes this fix, but beware that it isn't stable. You can install it doing `npm install soukai@next soukai-solid@next`.

Finally, looking at your examples I noticed that you are doing the following:

```js
const users = await User.from(webid).all();

```

I wouldn't recommend doing that, because you are saying "give me all the users from the webid container" (what you're passing to the `from` method is the container url, not the document url). To be honest, I'm even surprised that it works and I think it doesn't work in the next version because `webId` is not a container url. If you really wanted to do that, you should do it like this:

```js
const users = await User.from('https://username.solidcommunity.net/profile/').all();
```

But I don't think that's what you want, what I think you're trying to do is "give me this user". That would be done like this:

```js
const users = await User
    .from('https://username.solidcommunity.net/profile/')
    .find('https://username.solidcommunity.net/profile/card#me');
```

I know it can seem confusing, I'd like to improve the documentation and create some more educational materials at some point. But at the moment I'm focused on building apps. Feel free to ask any questions though!

**Comment by scenaristeur** [comment]
thxs ;-)
