### ISSUE TITLE
Couldn't make the example work with CSS

### ISSUE THREAD

**Issue by joeitu** [NoelDeMartin/soukai-solid#15]
Hi,

Would it be possible to be more precise on the example? 

More especially, how to set up the pod correctly? I have tried with CSS but it didn't worked. Would be great to have a simple, clear and full example of setting up a CSS instance and run soukai-solid with it. 

After setting up a CSS instance, creating a user `a` and creating a `people` container with full permission to the public ( read write manage permission ), I have tried to run the following:
```
import Soukai, { Model, InMemoryEngine } from "soukai";
import SoukaiSolid, { SolidEngine, SolidModel } from 'soukai-solid';

class User extends Model {}
class Person extends SolidModel {}

SoukaiSolid.loadSolidModels();
Soukai.loadModels({ Person });
Soukai.useEngine(new SolidEngine(window.fetch.bind(window)));

 Person.at('http://localhost:3055/a/people/').create({ name: 'John Doe' });

```

With 
```
    "soukai": "^0.4.1",
    "soukai-solid": "^0.4.2"
```

And I got the following error in my browser console:
```
soukai-solid.esm.js:1          GET http://localhost:3055/a/people/c4f1ee88-4dbc-44ee-9733-3b1085e8c21c 404 (Not Found)
```
What the `c4f1ee88-4dbc-44ee-9733-3b1085e8c21c ` document? did I missed a step?

Followed by: 
```
Uncaught (in promise) Error: Found illegal @type 'null'
    at EntryHandlerKeywordType.handle (EntryHandlerKeywordType.js:30:1)
    at async JsonLdParser.newOnValueJob (JsonLdParser.js:194:1)
    at async JsonLdParser.executeBufferedJobs (JsonLdParser.js:425:1)
```

**Comment by NoelDeMartin** [comment]
Hi there, thanks for opening an issue!

The example on this repo's documentation is very generic on purpose, authentication and specifics to different POD providers can get very messy and I'm trying to keep the documentation for this library simple. I'm also assuming that you know how to authenticate and create containers as necessary. If you want a more complex example, you can check out [Ramen](https://github.com/noeldemartin/ramen) which has been tested with different PODs and it's still relatively simple. Feel free to ask me anything about it, I'll be glad to document some parts that you find confusing.

Also, if you're not familiar with the basics of Solid I'd suggest that you look at this [Solid Hello World](https://github.com/0dataapp/hello/tree/main/solid) application I did a while ago. I wouldn't recommend making your first Solid app using Soukai.

Finally, I have been working on the library for a while since version `v0.4.2`. In fact, there are more than 100 new commits in the next version. So maybe you can try that to see if it fixes your problem? You can install it doing `npm install soukai@next soukai-solid@next`. I'm about to release a new app I've been working on and I'll also release the version `v0.5.0` of the library including all these changes. I think it'll still take me a couple of months though.

Now, solving your specific doubts:

> More especially, how to set up the pod correctly? I have tried with CSS but it didn't worked. Would be great to have a simple, clear and full example of setting up a CSS instance and run soukai-solid with it.

Eventually I'll add a Hello World example with soukai-solid as well, but for now if you look at [Ramen](https://github.com/NoelDeMartin/ramen) and [Solid Hello World](https://github.com/0dataapp/hello/tree/main/solid) it should be helpful. You'll notice that I'm using another library for these things, called `@noeldemartin/solid-utils`. But it isn't documented, I hope the examples and method names are self-explanatory though.

> I got the following error in my browser console: [...] 404 (Not Found)

This is probably not an error, the library is actually trying to get the document before it creates it to see if it doesn't exist. We discussed this in issue #11, so check it out for more info.

> What the `c4f1ee88-4dbc-44ee-9733-3b1085e8c21c` document? did I missed a step?

No, that's also the expected behaviour. You are not specifying the url you want for this new document, so it's just creating a random uuid. If you want to specify a url, you can do this for example:

```js
const john = new Person({ name: 'John Doe' });

john.mintUrl('http://localhost:3055/a/people/john');

await john.save('http://localhost:3055/a/people/');
```

Or you can also override the `newUrl` method [as I do in Media Kraken](https://github.com/NoelDeMartin/media-kraken/blob/main/src/models/soukai/Movie.ts#L215..L220).

> Uncaught (in promise) Error: Found illegal `@type` 'null'

This is actually something that looks like a bug. However, as I mentioned, I've changed a lot of the code in the new version so I suggest that you try it to see if it's fixed. If it doesn't work, let me know and I'll try to see what's going on.

Once of the things I definitely want to do before release is going through all the getting started instructions to see if they still work properly. When I wrote these I was using [NSS](https://github.com/nodeSolidServer/node-solid-server), so maybe something is different in [CSS](https://github.com/CommunitySolidServer/CommunitySolidServer) or other servers.

**Comment by joeitu** [comment]
On the readme example, is it normal on line 4 the solid model is empty? 

Shouldn't it be something like:
```
class Person extends SolidModel {

    static rdfsClasses = ['http://xmlns.com/foaf/0.1/Person'];
    static fields = {
        name: {
            type: FieldType.String,
            rdfProperty: 'http://xmlns.com/foaf/0.1/name',
        },
    };

}
```

**Comment by NoelDeMartin** [comment]
@joeitu Yes, you're right.

The example in the README technically works, but it assumes that the rdfsClass is `http://www.w3.org/ns/solid/terms#Person` and the `name` would be stored as `http://www.w3.org/ns/solid/terms#name`. All these definitions are optional, and the default rdfContext will be `http://www.w3.org/ns/solid/terms#`. But I haven't tried this in a while, because in real apps I do it as you mention in the example.

It is documented properly down below in the [RDF definitions](https://github.com/noeldemartin/soukai-solid#rdf-definitions) section, but I should update the first example (or at least clarify how it works).

By the way, I do have a deadline for when I'll release the next version, and update the documentation. I'll do it [before February 4th](https://fosdem.org/2023/schedule/event/sovcloud_from_zero_to_hero_with_solid/) :).

**Comment by NoelDeMartin** [comment]
I just released the new version and updated the documentation, so hopefully that's more clear now. Let me know if you have any more doubts!
