### ISSUE TITLE
model.all() can't return saved document  in the demo code

### ISSUE THREAD

**Issue by leeonfield** [NoelDeMartin/soukai-solid#3]
thx for you lib, follow querstion occurs when i get start

## version info
```shell
    "soukai": "^0.3.0",
    "soukai-solid": "^0.3.0",
```

## description
in the demo code which doc gives,`save` method works fine, but `all` method can't return the saved document while network already get the turtle data

```js
import Soukai from "soukai";
import { SolidModel, SolidEngine } from "soukai-solid";
import SolidAuthClient from "solid-auth-client";

const accountUrl = "https://myaccount.inrupt.net/news/";
class News extends SolidModel {}
Soukai.loadModels({ News });
Soukai.useEngine(new SolidEngine(SolidAuthClient.fetch.bind(SolidAuthClient)));
News.at(accountUrl);

const saveData = async () => {
  // this works
  await News.create({
    title: "latest",
    content: "content news",
    author: "leeon",
  });
};

const getData = async () => {
  // network get the data
  // but this method get []
  const list = await News.at(accountUrl).all();
};
```

**Comment by NoelDeMartin** [comment]
Hi there,

I see that you've closed the issue so maybe your problem is solved. But in case it is helpful, something to improve from your code is that you're not including [RDF definitions](https://github.com/NoelDeMartin/soukai-solid#rdf-definitions) in the models. I think it should work anyways, but I wouldn't recommend using such a model in a real application.

Maybe the problem was that a resource was created but given the lack of RDF definitions it doesn't have a proper shape and that causes problems when reading the model.

**Comment by leeonfield** [comment]
thank you so much for you reply,

 i solve the problem after realize lacking of RDF definitions.

`soukai-solid` is the tool what i looking for, thank you

**Comment by NoelDeMartin** [comment]
You're welcome, let me know how it goes :).

I've been working on some changes that I want to release soon (no time estimations though). They change some important things like the way resources are stored in the documents using a hash reference and using relative urls instead of absolute. Take a look at the [dev](https://github.com/NoelDeMartin/soukai-solid/tree/dev) branch or do `npm install soukai@next soukai-solid@next` if you want to try these out, but keep in mind it's a work in progress!

**Comment by leeonfield** [comment]
Thx for your reply.

Here is my code
```js
import Soukai from "soukai";
import { SolidModel, SolidEngine } from "soukai-solid";
import SolidAuthClient from "solid-auth-client";
const containerUrl = "https://myaccount.inrupt.net/news/";

class Report extends SolidModel {
  public static rdfContexts = {
    schema: "https://schema.org/",
  };
  public static rdfsClasses = ["schema:Report"];
  public static fields = {
    name: FieldType.String,
    author: FieldType.String,
  };
}
Soukai.loadModels({ Report });
Soukai.useEngine(new SolidEngine(SolidAuthClient.fetch.bind(SolidAuthClient)));
Report.at(containerUrl);

const saveData = async () => {
  // save document to containerUrl works fine
  await Report.create({
    name: "latest",
    author: "leeon",
  });
};

const getData = async () => {
  // return all the document in the containerUrl
  const list = await Report.at(containerUrl).all();
};
```

But a new question is how to deal(update,delete,get detail ) with the document directly. Following code is my current solution

```js
const fn = async () => {
  // get all document from the container Url
  const list = await Report.at(containerUrl).all();
    for (const iterator of list) {
      if (condition is true) {
        await iterator.delete();
        // or
        await iterator.update();
      }
    }
};
```
It will be great if the document provides more example

**Comment by NoelDeMartin** [comment]
I think your code should work for the most part, here's a couple of notes:

- The `author` field should be a `FieldType.Key`. If you look at [the schema.org documentation of the property](https://schema.org/author) it declares it as a reference to another resource, not as text. So it should be a url. It's fine to continue like this if you're just learning or tinkering with it, but for a real application this is important.
- The fields `author` and `name` are inferred to be `schema:author` and `schema:name` respectively, which is ok in this case. But keep it in mind in case you want to use a different name that doesn't match the schema.org documentation. You can use `rdfProperty` if you want to be explicit.
- The `delete` and `update` are ok, although the update will only change the `updatedAt` field because you're not changing anything in this example.
- I also assume this is an example, for a real application you wouldn't hard-code the url of the container. You should get it from the [Type Index Registry](https://github.com/solid/solid/blob/master/proposals/data-discovery.md#type-index-registry) or ask the user.

If you want to see some example models, take a look at these places (I'll add this to the documentation :D):
- [Test models](https://github.com/NoelDeMartin/soukai-solid/tree/master/tests/stubs) in this project (you can look at [test files](https://github.com/NoelDeMartin/soukai-solid/blob/master/src/models/SolidModel.test.ts) to see how they are used).
- [Models in Media Kraken](https://github.com/NoelDeMartin/media-kraken/tree/main/src/models/soukai).
- [Models in Solid Focus](https://github.com/NoelDeMartin/solid-focus/tree/master/src/models/soukai). I haven't worked on this one for a while, so there are some things I'd do differently today. But I still use it every day and it works :).

**Comment by leeonfield** [comment]
Very  helpful suggestions, thank a lot.

Sure, it's just a demo example to show my solution. I have found ` Media Kraken` and `Solid Focus` from [solid app list](https://inrupt.com/solid-app-listing) before,and read their source code now.

I wonder is it possible to get data from source url directly by `soukai-solid` other than through the container url ?

For example, I can use `Model.all()` get all documents contain in `https:demo.solid.net/movies/`.
Is it possible  to use `soukai-solid` directly get  movie data from `https:demo.solid.net/movies/12-Angry-Men` ?

**Comment by NoelDeMartin** [comment]
> I wonder is it possible to get data from source url directly by `soukai-solid` other than through the container url ?
> 
> For example, I can use `Model.all()` get all documents contain in `https:demo.solid.net/movies/`.
> Is it possible to use `soukai-solid` directly get movie data from `https:demo.solid.net/movies/12-Angry-Men` ?

It would technically be possible, but the codebase is not prepared for that. `Model` for example is an abstract class, so you'd need to extend the class anyways. I think for that use-case, where you're working with data and you don't know the shape, it's better to use something like [ldflex](https://solid.github.io/query-ldflex/).

I'm not sure because the apps I've been working on always have a known data structure, so I haven't found the need to do that kind of generalisation.

**Comment by leeonfield** [comment]
Get that, thank you so much Orz
