### ISSUE TITLE
vuejs template render : cyclic object value

### ISSUE THREAD

**Issue by scenaristeur** [NoelDeMartin/soukai-solid#7]
Hi @NoelDeMartin , 
I think soukai-solid could fit some needs for my current project, but I got some issue when trying to loop with v-for on workspaces with "cyclic object value" (see last pic) 

```
  <ul>
      <li v-for="(sws,i) in souk_ws" :key="i">
        {{sws.name}}<br>
        {{sws.createdAt}}<br>
        {{sws}}
      </li>
    </ul>
```

with  https://github.com/scenaristeur/ess-table/blob/main/src/views/WorkspacesView.vue#L92

![image](https://user-images.githubusercontent.com/4020744/104737830-10bb4380-5745-11eb-954f-676eff3aa672.png)

i've tryed some test with flatted https://www.npmjs.com/package/flatted but no succes

![image](https://user-images.githubusercontent.com/4020744/104737145-2c721a00-5744-11eb-9398-b6d6edd86886.png)

Could you please tell me How you deal with circular references ? 

![image](https://user-images.githubusercontent.com/4020744/104738505-e918ab00-5745-11eb-8760-f5cc0fa14018.png)

thxs . 

Edit : For the moment I got it working with .map() 

```
     this.souk_ws = souk_ws.map(x => ({'name' : x.name, 'createdAt': x.createdAt}))
```

But i'd eventually like to pass each object to subcomponents

**Comment by NoelDeMartin** [comment]
Hi there,

I'm not sure what's the issue you're having, but for what I can tell looking at your code, it seems like you're trying to render a model like this: `{{ sws }}`. I'm not sure why you are doing that, but if what you want is to get the model attributes you should be doing `sws.getAttributes()`. And if you want to render the attributes, I think you should do something like this: `{{ JSON.stringify(sws.getAttributes())` (although I'd suggest that you use a computed property for that). Not sure if that's related with your problem.

As far as I can tell (I could be missing something), the only circular references in models are related models (using [soukai relationships](https://soukai.js.org/guide/defining-models.html#relationships)). But I don't see any relations defined in your Workspace model, and I've been using models with relationships in my Vue apps without any problems.

In any case, this library doesn't know anything about Vue, so you should phrase your issue in a framework agnostic context so that I can help you.
