### ISSUE TITLE
Soukai relations

### ISSUE THREAD

**Issue by scenaristeur** [NoelDeMartin/soukai-solid#8]
Hi, i'd like to use Soukai-solid but i'm a little bit lost with Relations : 
I'm working on a Airtable like App on Solid : 

- workspaces instances at https://spoggy-test5.solidcommunity.net/public/table/workspaces/  https://www.dublincore.org/specifications/dublin-core/dcmi-terms/hasPart / hasMany bases instances at https://spoggy-test5.solidcommunity.net/public/table/bases/
- each base instances can ...hasPart  / hasMany Tables instances at https://spoggy-test5.solidcommunity.net/public/table/tables/
- tables instances hasPart Records instances at https://spoggy-test5.solidcommunity.net/public/table/records/
- records instances like https://spoggy-test5.solidcommunity.net/public/table/records/097d3d66-e2ff-4c26-afe3-52168b801b66.ttl hasMany Notes, Files or other fields defined in in parent Table  like here https://spoggy-test5.solidcommunity.net/public/table/tables/22cb4d75-8f50-4e3d-b546-f1bb0bd589dc.ttl

Could you please tell me how to build these relations ? or at least the workspaces to bases ? 
Or tell me if my request is not limpid 
Thxs

**Comment by NoelDeMartin** [comment]
Sure, happy to help, let's see what I can do.

I've been thinking what's the best way to document data modeling in Solid apps, so far I've been doing some kind of class diagrams.

Here's the one for [Solid Focus](https://github.com/NoelDeMartin/solid-focus/tree/master/docs#data-schema):

![SolidFocus](https://user-images.githubusercontent.com/1517677/104807522-e9658480-57df-11eb-884b-bf28007aaa91.jpeg)

And here's the one for [Media Kraken](https://github.com/NoelDeMartin/media-kraken/tree/main/docs#data-schema):

![MediaKraken](https://user-images.githubusercontent.com/1517677/104807520-e66a9400-57df-11eb-8265-8fe8b956d9a1.png)

What I'm trying to do in these is define how each model maps fields to RDF properties, and which fields/RDF properties describe the relationships. I know it can be confusing, so hopefully having conversations with other developers like you will help me improve the way to communicate how Soukai and Solid work together :).

If you are going to look at those examples, Media Kraken is a much better reference because I built it after Solid Focus and I learned a lot of things I didn't know then.

Now, looking at your questions here's what I understand:

You want a `Workspace` model. Instances of this model are stored in documents inside of `public/table/workspaces`. This path should actually work using [the type index](https://github.com/solid/solid/blob/master/proposals/data-discovery.md#type-index-registry), which I'm not using in Solid Focus because I didn't understand it then. If you're still learning, it's ok to hard-code `/public/table/workspaces` to simplify, but I'd encourage you to use the type index for the final version.

You also want `Base`, `Table`, and `Record` models. Same comments as the `Workspace` model.

You want each Workspace to have 0, 1 or more Bases (so, it's a [one-to-many relationship](https://en.wikipedia.org/wiki/One-to-many_(data_model))). And you want this relationship to be described using the `dcmi:hasPart` property in the Workspace model. I have a table in [the documentation](https://soukai.js.org/guide/defining-models.html#relationships) to help decide which relationship to use, in this case you would say "one Workspace **references** **multiple** Bases". So, looking at the table in the docs, you can see that you should use the `belongsToMany` relationship. As an example, if you wanted to do it the other way around (Base references Workspaces using the `dcmi:isPartOf` property) you would say "one Workspace **is referenced by** **multiple** Bases", and the relationship would be `hasMany`. You would also say that "one Base **is referenced by** **one** Workspace", so the relationship from Tables to Workspaces should be `hasOne` (you dont't have to define it if you don't need it).

Same idea for the relationships between Bases, Tables and Records.

Looking at the Table document, I'd encourage you to use proper RDF fields to define the field list, instead of a JSON-encoded string like you are using now. But I understand that you want the possible fields of a Record to be declared in the parent Table. I think the best way to do that would be to create a new model called `Field`, and each Record would have many Fields associated (one for each field defined in the parent Table). In this case, you may want to store the Fields in the same document as the Record. This is similar to what I do with Movies in Media Kraken, the WatchAction models are stored in the same document as the Movie.

Here's a very rough example of what it could look in practice. Please, take this as pseudocode because I'm just writing this and I haven't run the code:

Workspace model:

```js
class Workspace extends SolidModel {

    static rdfContexts = {
        dbpedia: 'http://dbpedia.org/ontology/',
        dcmi: 'https://www.dublincore.org/specifications/dublin-core/dcmi-terms/',
    };

    static rdfsClasses = ['dbpedia:Workspace'];

    static fields = {
        name: {
            type: FieldType.String,
            rdfProperty: 'rdfs:label',
        },
        parts: {
            type: FieldType.Array,
            rdfProperty: 'dcmi:hasPart'
            items: FieldType.Key,
        },
    };

    basesRelationship() {
        return this.belongsToMany(Base, 'parts');
    }

}
```

Base model:

```js
class Base extends SolidModel {

    static rdfContexts = {
        dbpedia: 'http://dbpedia.org/ontology/',
        dcmi: 'https://www.dublincore.org/specifications/dublin-core/dcmi-terms/',
    };

    static rdfsClasses = ['dbpedia:DataBase'];

    static fields = {
        name: {
            type: FieldType.String,
            rdfProperty: 'rdfs:label',
        },
        parts: {
            type: FieldType.Array,
            rdfProperty: 'dcmi:hasPart'
            items: FieldType.Key,
        },
    };

    workspaceRelationship() {
        // This "parts" is the name of the field in the Workspace model.
        return this.hasOne(Workspace, 'parts');
    }

    tablesRelationship() {
        // This "parts" is the name of the field in the Base model.
        return this.belongsToMany(Table, 'parts');
    }

}
```
I hope this is helpful, let me know how it goes. We can leave this issue open to follow up :).

Also, I haven't talked about containers, so keep that in mind. If all of this relationship stuff is getting over your head, you don't have to use it. You can just create the models manually and just have a plain javascript array with the related models when it makes sense.

**Comment by scenaristeur** [comment]
Hi @NoelDeMartin , thxs for the care of my issue... 
First about TypeIndexes, i know them but i think it's a lot of questions (which DocumentType, Private, public...), lot of dev and lot of requests for a poor benefit results so I rather prefer explore the edges of the country with other explorators ...

The relations I expect are two ways : a workspace have many bases (whose could be local to the POD or remote on another POD) same for Tables . 
So for example a Wine Table with records  of wine could be referenced in a base on a grocery POD as ProductTable, and used in 
restaurant POD as a Buying table in Budget Base... but this is for a later implementation ;-)

By the way, I need two way reference first as desecending from global to local concept, and in case of moving / deleting  : if you delete a table, the base referencing it must be updated.

And in fact there could also be someone who want to put in a Table a list of Workspaces ... ;-)

So i think the best way for my use case is to kick off the relationships or add a Collection Concept that extend SolidModel and all my Model extend that Collection, as they all got the same properties dcmi:hasPart, rdfs:lable, url

I was looking at vue-mc too https://vuemc.io/#basic-usage which deal with Collection, but they lack the Solid part for fetching, saving...

Next, i saw that Soukai can deal with localstorage (https://codesandbox.io/s/soukai-example-users-posts-3gryb?from-embed) , so  do you have an idea how to use service-worker as a caching service as here https://serviceworke.rs/strategy-cache-update-and-refresh_controlled_doc.html ?

thxs for your help,

**Comment by NoelDeMartin** [comment]
> about TypeIndexes, i know them but i think it's a lot of questions (which DocumentType, Private, public...), lot of dev and lot of requests for a poor benefit results so I rather prefer explore the edges of the country with other explorators ...

I understand that you see it that way, but I don't agree that it has poor benefits. IMO this is at the core of Solid, because things like this make other apps work with the data that your app is creating. Of course, if you don't care about interoperability and only care about your app working that's fine, but then you'd be better of using a normal database and not getting all the complexity of working with Solid.

But I understand that you're still learning so it's ok if you don't do it for now. As I said, I didn't do it in my first app and I still have to update it :).

> in case of moving / deleting : if you delete a table, the base referencing it must be updated.

I have implemented some of this in relationships. For example, you can define the relationship in the `Workspace` model like this:

```js
basesRelationship() {
    return this.belongsToMany(Base, 'parts').onDelete('cascade');
}
```

But so far that's the only thing implemented, I haven't implemented support for moving and other scenarios. I've been developing this library as needed for developing my applications, and I didn't need to implement other use cases.

> So i think the best way for my use case is to kick off the relationships or add a Collection Concept that extend SolidModel and all my Model extend that Collection

I'm not sure if you can extend models at the moment. You can, but I don't think the field definitions will be used from parent classes. If you decide to go this route, I'd suggest using helper methods instead, something like:

```js
class Workspace extends SolidModel {

    static fields = getCollectionFieldsDefinition({
        // Define here fields specific to Workspace model.
    });

}
```

> Next, i saw that Soukai can deal with localstorage (https://codesandbox.io/s/soukai-example-users-posts-3gryb?from-embed) , so do you have an idea how to use service-worker as a caching service as here https://serviceworke.rs/strategy-cache-update-and-refresh_controlled_doc.html ?

I faced something similar to this in Media Kraken, and in the end I decided to do it in the application layer of the stack (meaning that I implemented it in Media Kraken, not in Soukai). Maybe at some point I could add something in Soukai to handle caching, but I still want to experiment more with it before I do something generic. In the end what I did was specific to my application, but maybe it's useful if you want to take a look. I am using a service worker and storing the data in IndexedDB (localStorage is not available within a service worker). You can find the source code [here](https://github.com/NoelDeMartin/media-kraken/blob/main/src/workers/LoadMediaWorker.ts#L116).

**Comment by NoelDeMartin** [comment]
On the last point in my previous comment, I just realized I am actually using a "web worker" not a "service worker", which are different things :sweat_smile:.

Keeping that in mind, what a service worker does is sitting in front of the network so the rest of your application wouldn't notice that you're doing it (from the point of view of the application, it's actually doing a network request). In any case, I think we are talking about the same use-case because I am using the web worker to do caching. It's only more specific to the application, instead of caching network requests.

Sorry if that was confusing.

**Comment by NoelDeMartin** [comment]
Hey, I just released a new version and updated the documentation. Hopefully with that and the discussion we've had it's more clear now. In the future I may do more educational materials, but for now I think I'll leave it at that (it's not like many people is using the library anyways).

If you have any more doubts, let me know!
