### ISSUE TITLE
Unclear how relationships work

### ISSUE THREAD

**Issue by vanhumbeecka** [NoelDeMartin/soukai-solid#9]
Hi there,
Based on your examples and documentation, I'm trying to run a basic test.
However, it's unclear to me what's wrong with this.
I'm getting a `Couldn't find document with id contactpoints/630c275c-7b1f-4bee-b3f3-216c0a595709` error, even though when I'm printing out the inmemory engine, it's right there.

The models:
```
import { FieldType, Relation, SingleModelRelation } from 'soukai'
import { SolidHasManyRelation, SolidModel } from 'soukai-solid'

export class Person extends SolidModel {
  static rdfContexts = {
    'schema': 'http://schema.org'
  }
  static rdfsClasses = ['schema:Person']
  static fields = {
    name: {
      type: FieldType.String,
      rdfProperty: 'schema:name'
    }
  }

  public contactPoints?: ContactPoint[]
  public relatedContactPoints!: SolidHasManyRelation<Person, ContactPoint, typeof ContactPoint>

  public saveContactPoint(contactPoint: ContactPoint): Promise<void> {
    return this.relatedContactPoints.save(contactPoint)
  }

  contactPointsRelationship(): Relation {
    return this.hasMany(ContactPoint, 'personId')
  }
}

export class ContactPoint extends SolidModel {
  static rdfContexts = {
    'schema': 'http://schema.org'
  }
  static rdfsClasses = ['schema:ContactPoint']
  static fields = {
    personId: {
      type: FieldType.Key,
      required: true
    },
    email: {
      type: FieldType.String, rdfProperty: 'schema:email'
    }
  }

  personRelationship(): SingleModelRelation {
    return this.belongsToOne(Person, 'personId')
  }
}
```

And the Jest test, which fails:
```
it(`Person relationships should be stored`, async () => {
    const person = await Person.create<Person>({
      name: "Jeff"
    })


    person.setRelationModels('contactPoints', []); // <-- is this correct?

    const contact = await ContactPoint.create<ContactPoint>({
      personId: person.getIdAttribute(), // <-- If I don't supply this, he complains of missing property
      email: "test@example.com"
    })

    console.log(engine.database) // looks ok

    await person.saveContactPoint(contact) // <-- fails with error above
 
    const contactPoints = await person.loadRelation('contactPoints')
    expect(contactPoints).toHaveLength(1)
  })
```

There are still a lot of unknowns to me here. Any guidance is much appreciated.

**Comment by vanhumbeecka** [comment]
Furthermore, I tried recreating your example from the readme, related to Band-members.
There seems to be an issue in the `initialize` method: I can't get a `console.log` AFTER the `await this.loadRelation('person'). 

```
export class ContactPoint extends SolidModel {
  static rdfContexts = {
    'schema': 'http://schema.org'
  }
  static rdfsClasses = ['schema:ContactPoint']
  static fields = {
    personId: {
      type: FieldType.Key,
      rdfProperty: 'schema:homeLocation'
    },
    email: {
      type: FieldType.String, rdfProperty: 'schema:email'
    }
  }

  public person?: Person
  public relatedPerson?: BelongsToOneRelation

  async initialize(attributes: Attributes, exists: boolean) {
    super.initialize(attributes, exists);

    console.log('this is fine', this.getAttribute('email')); // <-- gets called
    await this.loadRelation('person');
    console.log('this is also fine', this.getRelationModels('person')); // <-- never gets called
  }

  personRelationship(): SingleModelRelation {
    return this.belongsToOne(Person, 'personId')
  }
}
```

And running something like:
```
const contact = await ContactPoint.at(containerUrl).create<ContactPoint>({
      email: "test@example.com"
    })
```

Not sure if these are related?

**Comment by NoelDeMartin** [comment]
Hi there!

Thanks for opening the issue, you're right that this error shouldn't happen and debugging your test I could find a bug :). However, your test still fails after fixing the bug with a different error, the `contactPoints` array would have length 0. Let me explain.

First, the bug. With Solid, Soukai collections are container urls, and ids are resource urls. That's true even using non-Solid engines, like InMemoryEngine. In a real Solid app, you'd always specify the collection manually because the default collection name (in your case "persons" and "contactpoints") will not be a valid url. Because of that, sometimes models guess the collection url from their id. For example, if you have a model with id `https://my-pod.com/foo/bar/something#it`, the container url [will be guessed](https://github.com/NoelDeMartin/soukai-solid/blob/main/src/models/SolidModel.ts#L489) to be `https://my-pod.com/foo/bar/`. The bug is that the default collections don't end with a trailing slash /, so when it tries to guess the collection from `contactpoints/630c275c-7b1f-4bee-b3f3-216c0a595709` it guesses `contactpoints/` and it should be "contactpoints". Furthermore, `contactpoints/` is not a valid url either so it should be something like `local://contactpoints/`. The fix is that auto-generated collection names for Solid models should be valid urls. Until that fix is released, you can work around that by declaring them manually in your models: `static collection = "local://contactpoints/";`.

Now, why would your test fail anyways? Because hasMany relationships, in Solid, only work with keys stored in the same document. This is explained in [a note in the README](https://github.com/NoelDeMartin/soukai-solid#hasmany).

Your second example with initialize, I'm guessing it fails because something goes wrong calling loadRelation and the error is silenced (because the initialize method is not asynchronous to being with, so when you make it asynchronous the reject is uncaught). Try adding a try/catch in there and you should see what's the issue. But I wouldn't write asynchronous code in there (initialize is part of the constructor, and object constructors should never cause side-effects). (**edit:** I just noticed there is an example of calling async methods on the initialize in the docs. That's wrong, I'll update the docs xD)

I hope this is helpful, and you understand better how the library works. Feel free to ask any more questions :).

Here's your code tweaked with a couple of comments and how I'd do it:

```ts
class Person extends SolidModel {

    // Workaround until the bug is fixed
    static collection = 'local://persons/';

    static rdfContexts = { schema: 'http://schema.org' };
    static rdfsClasses = ['Person']
    static fields = {
        name: FieldType.String,
    };

    contactPoints?: ContactPoint[]
    relatedContactPoints!: SolidHasManyRelation<Person, ContactPoint, typeof ContactPoint>

    contactPointsRelationship(): Relation {
        // Notice that I'm calling usingSameDocument so that the hasMany relationship works
        return this.hasMany(ContactPoint, 'personId').usingSameDocument()
    }

}

class ContactPoint extends SolidModel {

    // Workaround until the bug is fixed
    static collection = 'local://contactpoints/';

    static rdfContexts = { 'schema': 'http://schema.org' };
    static rdfsClasses = ['ContactPoint'];
    static fields = {
        personId: {
            type: FieldType.Key,
            required: true
        },
        email: FieldType.String,
    };

}

describe('NoelDeMartin/soukai-solid#9', () => {

    let engine;

    beforeEach(() => {
        engine = new InMemoryEngine();

        Soukai.useEngine(engine);
        Soukai.loadModels({ Person, ContactPoint });
    });

    it(`Person relationships should be stored`, async () => {
        const person = await Person.create<Person>({ name: 'Jeff' });

        // Yes, you need to do this but I should probably implement something to make this unnecessary,
        // because the Model has just been created so we already know it's empty.
        person.setRelationModels('contactPoints', []);

        // No need to provide person Id, the relationship already knows it :)
        const contactpoint = await person.relatedContactPoints.create({ email: 'test@example.com' });

        // The model has also been added to the relationship!
        expect(person.contactPoints).toHaveLength(1);
        expect(person.contactPoints![0]).toBe(contactpoint);

        // Inspect the database now if you want to see how it looks
        console.log(JSON.stringify(engine.database));

        // And this is how you'd retrieve the data later on:
        const persons = await Person.all<Person>();

        await Promise.all(persons.map(person => person.loadRelation('contactPoints')));

        expect(persons).toHaveLength(1);
        expect(persons[0].contactPoints).toHaveLength(1);
        expect(persons[0].contactPoints![0].email).toEqual('test@example.com');
    });

});
```

**Comment by vanhumbeecka** [comment]
Cool, thanks for taking the time to investigate this!

**Comment by NoelDeMartin** [comment]
Hey, I just released a new version and updated the documentation. Hopefully with that and the discussion we've had it's more clear now. In the future I may do more educational materials, but for now I think I'll leave it at that (it's not like many people is using the library anyways).

If you have any more doubts, let me know!
